# Teams
This dataset describes all the soccer teams in seven prominent soccer competitions (Italian, Spanish, German, French and English first divisions, World Cup 2018, European Cup 2016). It consists of the following fields:

- city: the city where the team is located. For national teams it is the capital of the country;
- name: the common name of the team;
- area: information about the geographic area associated with the team;
- wyId: the identifier of the team, assigned by Wyscout;
- officialName: the official name of the team (e.g., Juventus FC);
- type: the type of the team. It is "club" for teams in the competitions for clubs and "national" for the teams in international competitions;

# Events
This dataset describes all the events that occur during each match. Each event refers to a ball touch and contains the following information:

- eventId: the identifier of the event's type. Each eventId is associated with an event name (see next point);
- eventName: tteamIdhe name of the event's type. There are seven types of events: pass, foul, shot, duel, free kick, offside and touch;
- subEventId: the identifier of the subevent's type. Each subEventId is associated with a subevent name (see next point);
- subEventName: the name of the subevent's type. Each event type is associated with a different set of subevent types;
- tags: a list of event tags, each one describes additional information about the event (e.g., accurate). Each event type is associated with a different set of tags;
- eventSec: the time when the event occurs (in seconds since the beginning of the current half of the match);
- id: a unique identifier of the event;
- matchId: the identifier of the match the event refers to. The identifier refers to the field "wyId" in the match dataset;
- matchPeriod: the period of the match. It can be "1H" (first half of the match), "2H" (second half of the match), "E1" (first extra time), "E2" (second extra time) or "P" (penalties time);
- playerId: the identifier of the player who generated the event. The identifier refers to the field "wyId" in a player dataset;
- positions: the origin and destination positions associated with the event. Each position is a pair of coordinates (x, y). The x and y coordinates are always in the range [0, 100] and indicate the percentage of the field from the perspective of the attacking team. In particular, the value of the x coordinate indicates the event's nearness (in percentage) to the opponent's goal, while the value of the y coordinates indicates the event's nearness (in percentage) to the right side of the field;
- teamId: the identifier of the player's team. The identifier refers to the field "wyId" in the team dataset.

# Matches
This dataset describes all the matches made available. Each match is a document consisting of the following fields:

- competitionId: the identifier of the competition to which the match belongs to. It is a integer and refers to the field "wyId" of the competition document;
- date and dateutc: the former specifies date and time when the match starts in explicit format (e.g., May 20, 2018 at 8:45:00 PM GMT+2), the latter contains the same information but in the compact format YYYY-MM-DD hh:mm:ss;
- duration: the duration of the match. It can be "Regular" (matches of regular duration of 90 minutes + stoppage time), "ExtraTime" (matches with supplementary times, as it may happen for matches in continental or international competitions), or "Penalities" (matches which end at penalty kicks, as it may happen for continental or international competitions);
- gameweek: the week of the league, starting from the beginning of the league;
- label: contains the name of the two clubs and the result of the match (e.g., "Lazio - Internazionale, 2 - 3");
- roundID: indicates the match-day of the competition to which the match belongs to. During a competition for soccer clubs, each of the participating clubs plays against each of the other clubs twice, once at home and once away. The matches are organized in match-days: all the matches in match-day i are played before the matches in match-day i + 1, even tough some matches can be anticipated or postponed to facilitate players and clubs participating in Continental or Intercontinental competitions. During a competition for national teams, the "roundID" indicates the stage of the competition (eliminatory round, round of 16, quarter finals, semifinals, final);
- seasonId: indicates the season of the match;
- status: it can be "Played" (the match has officially finished), "Cancelled" (the match has been canceled for some reason), "Postponed" (the match has been postponed and no new date and time is available yet) or "Suspended" (the match has been suspended and no new date and time is available yet);
- venue: the stadium where the match was held (e.g., "Stadio Olimpico");
- winner: the identifier of the team which won the game, or 0 if the match ended with a draw;
- wyId: the identifier of the match, assigned by Wyscout;
- teamsData: it contains several subfields describing information about each team that is playing that match: such as lineup, bench composition, list of substitutions, coach and scores:
- hasFormation: it has value 0 if no formation (lineups and benches) is present, and 1 otherwise;
- score: the number of goals scored by the team during the match (not counting penalties);
- scoreET: the number of goals scored by the team during the match, including the extra time (not counting penalties);
- scoreHT: the number of goals scored by the team during the first half of the match;
- scoreP: the total number of goals scored by the team after the penalties;
- side: the team side in the match (it can be "home" or "away");
- teamId: the identifier of the team;
- coachId: the identifier of the team's coach;
- bench: the list of the team's players that started the match in the bench and some basic statistics about their performance during the match (goals, own goals, cards);
- lineup: the list of the team's players in the starting lineup and some basic statistics about their performance during the match (goals, own goals, cards);
- substitutions: the list of team's substitutions during the match, describing the players involved and the minute of the substitution.

# Competitions
This dataset describes seven major soccer competitions (Italian, Spanish, German, French, English first divisions, World cup 2018, European cup 2016). Each competition is a document consisting of the following fields:

area: it denotes the geographic area associated with the league as a sub-document, using the ISO 3166-1 specification (https://www.iso.org/iso-3166-country-codes.html);
format: the format of the competition. All competitions for clubs have value "Domestic league". The competitions for national teams have value "International cup";
- name: the official name of the competition (e.g., Italian first division, Spanish first division, World Cup, etc.);
- type: the typology of the competition. It is "club" for the competitions for clubs and "international" for the competitions for national teams (World Cup 2018, European Cup 2016);
- wyId: the unique identifier of the competition, assigned by Wyscout.

# 积分规则
赢一局加三分，输一局加零分，平一局加一分

In [62]:
import pandas as pd
import numpy as np
df_matches_Eng = pd.read_json('matches/matches_England.json')
print(df_matches_Eng.columns)
for i in range(len(df_matches_Eng)):
    if 'Everton' in df_matches_Eng['label'][i]:
        print(df_matches_Eng['label'][i], df_matches_Eng['teamsData'][i].keys(), df_matches_Eng['winner'][i])

Index(['competitionId', 'date', 'dateutc', 'duration', 'gameweek', 'label',
       'referees', 'roundId', 'seasonId', 'status', 'teamsData', 'venue',
       'winner', 'wyId'],
      dtype='object')
West Ham United - Everton, 3 - 1 dict_keys(['1623', '1633']) 1633
Everton - Southampton, 1 - 1 dict_keys(['1623', '1619']) 0
Huddersfield Town - Everton, 0 - 2 dict_keys(['1623', '1673']) 1623
Everton - Newcastle United, 1 - 0 dict_keys(['1623', '1613']) 1623
Swansea City - Everton, 1 - 1 dict_keys(['1623', '10531']) 0
Everton - Liverpool, 0 - 0 dict_keys(['1623', '1612']) 0
Everton - Manchester City, 1 - 3 dict_keys(['1623', '1625']) 1625
Stoke City - Everton, 1 - 2 dict_keys(['1623', '1639']) 1623
Everton - Brighton & Hove Albion, 2 - 0 dict_keys(['1623', '1651']) 0
Burnley - Everton, 2 - 1 dict_keys(['1623', '1646']) 1646
Watford - Everton, 1 - 0 dict_keys(['1623', '1644']) 0
Everton - Crystal Palace, 3 - 1 dict_keys(['1623', '1628']) 1623
Arsenal - Everton, 5 - 1 dict_keys(['1609', '1623']) 1609
Everton - Leicester City, 2 - 1 dict_keys(['1623', '1631']) 1623
Everton - West Bromwich Albion, 1 - 1 dict_keys(['1623', '1627']) 0
Tottenham Hotspur - Everton, 4 - 0 dict_keys(['1623', '1624']) 1624
Everton - Manchester United, 0 - 2 dict_keys(['1623', '1611']) 1611
AFC Bournemouth - Everton, 2 - 1 dict_keys(['1623', '1659']) 1659
West Bromwich Albion - Everton, 0 - 0 dict_keys(['1623', '1627']) 0
Everton - Chelsea, 0 - 0 dict_keys(['1623', '1610']) 0
Everton - Swansea City, 3 - 1 dict_keys(['1623', '10531']) 1623
Newcastle United - Everton, 0 - 1 dict_keys(['1623', '1613']) 1623
Liverpool - Everton, 1 - 1 dict_keys(['1623', '1612']) 0
Everton - Huddersfield Town, 2 - 0 dict_keys(['1623', '1673']) 1623
Everton - West Ham United, 4 - 0 dict_keys(['1623', '1633']) 1623
Southampton - Everton, 4 - 1 dict_keys(['1623', '1619']) 1619
Crystal Palace - Everton, 2 - 2 dict_keys(['1623', '1628']) 0
Everton - Watford, 3 - 2 dict_keys(['1623', '1644']) 1623
Leicester City - Everton, 2 - 0 dict_keys(['1623', '1631']) 1631
Everton - Arsenal, 2 - 5 dict_keys(['1623', '1609']) 1609
Brighton & Hove Albion - Everton, 1 - 1 dict_keys(['1623', '1651']) 0
Everton - Burnley, 0 - 1 dict_keys(['1623', '1646']) 1646
Everton - AFC Bournemouth, 2 - 1 dict_keys(['1623', '1659']) 1623
Manchester United - Everton, 4 - 0 dict_keys(['1623', '1611']) 1611
Everton - Tottenham Hotspur, 0 - 3 dict_keys(['1623', '1624']) 1624
Chelsea - Everton, 2 - 0 dict_keys(['1623', '1610']) 1610
Manchester City - Everton, 1 - 1 dict_keys(['1623', '1625']) 0
Everton - Stoke City, 1 - 0 dict_keys(['1623', '1639']) 1623

In [110]:
df_matches_Eng

,competitionId,date,dateutc,duration,gameweek,label,referees,roundId,seasonId,status,teamsData,venue,winner,wyId
0,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Burnley - AFC Bournemouth, 1 - 2","[{'refereeId': 385705, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",Turf Moor,1659,2500089
1,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Crystal Palace - West Bromwich Albion, 2 - 0","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1628': {'scoreET': 0, 'coachId': 8357, 'side...",Selhurst Park,1628,2500090
2,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Huddersfield Town - Arsenal, 0 - 1","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",The John Smith's Stadium,1609,2500091
3,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Liverpool - Brighton & Hove Albion, 4 - 0","[{'refereeId': 385704, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",Anfield,1612,2500092
4,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Manchester United - Watford, 1 - 0","[{'refereeId': 381853, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 93112, 'sid...",Old Trafford,1611,2500093
5,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Newcastle United - Chelsea, 3 - 0","[{'refereeId': 384888, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1613': {'scoreET': 0, 'coachId': 210700, 'si...",St. James' Park,1613,2500094
6,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Southampton - Manchester City, 0 - 1","[{'refereeId': 385911, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1625': {'scoreET': 0, 'coachId': 267136, 'si...",St. Mary's Stadium,1625,2500095
7,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Swansea City - Stoke City, 1 - 2","[{'refereeId': 378952, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 32573, 'si...",Liberty Stadium,1639,2500096
8,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"Tottenham Hotspur - Leicester City, 5 - 4","[{'refereeId': 378951, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1631': {'scoreET': 0, 'coachId': 209010, 'si...",Wembley Stadium,1624,2500097
9,364,"May 13, 2018 at 4:00:00 PM GMT+2",2018-05-13 14:00:00,Regular,38,"West Ham United - Everton, 3 - 1","[{'refereeId': 408156, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1623': {'scoreET': 0, 'coachId': 8541, 'side...",London Stadium,1633,2500098
10,364,"May 10, 2018 at 8:45:00 PM GMT+2",2018-05-10 18:45:00,Regular,31,"West Ham United - Manchester United, 0 - 0","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1633': {'scoreET': 0, 'coachId': 8235, 'side...",London Stadium,0,2500028
11,364,"May 9, 2018 at 9:00:00 PM GMT+2",2018-05-09 19:00:00,Regular,31,"Manchester City - Brighton & Hove Albion, 3 - 1","[{'refereeId': 385705, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",Etihad Stadium,1625,2500024
12,364,"May 9, 2018 at 9:00:00 PM GMT+2",2018-05-09 19:00:00,Regular,31,"Tottenham Hotspur - Newcastle United, 1 - 0","[{'refereeId': 385915, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1613': {'scoreET': 0, 'coachId': 210700, 'si...",Wembley Stadium,1624,2500027
13,364,"May 9, 2018 at 8:45:00 PM GMT+2",2018-05-09 18:45:00,Regular,31,"Leicester City - Arsenal, 3 - 1","[{'refereeId': 408156, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",King Power Stadium,1631,2500022
14,364,"May 9, 2018 at 8:45:00 PM GMT+2",2018-05-09 18:45:00,Regular,35,"Chelsea - Huddersfield Town, 1 - 1","[{'refereeId': 381853, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1610': {'scoreET': 0, 'coachId': 272869, 'si...",Stamford Bridge,0,2500062
15,364,"May 8, 2018 at 8:45:00 PM GMT+2",2018-05-08 18:45:00,Regular,31,"Swansea City - Southampton, 0 - 1","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 32573, 'si...",Liberty Stadium,1619,2500026
16,364,"May 6, 2018 at 5:30:00 PM GMT+2",2018-05-06 15:30:00,Regular,37,"Arsenal - Burnley, 5 - 0","[{'refereeId': 385911, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",Emirates Stadium,1609,2500080
17,364,"May 6, 2018 at 5:30:00 PM GMT+2",2018-05-06 15:30:00,Regular,37,"Chelsea - Liverpool, 1 - 0","[{'refereeId': 378952, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1612': {'scoreET': 0, 'coachId': 14791, 'sid...",Stamford Bridge,1610,2500082
18,364,"May 6, 2018 at 2:30:00 PM GMT+2",2018-05-06 12:30:00,Regular,37,"Manchester City - Huddersfield Town, 0 - 0","[{'refereeId': 385909, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1625': {'scoreET': 0, 'coachId': 267136, 'si...",Etihad Stadium,0,2500085
19,364,"May 5, 2018 at 6:30:00 PM GMT+2",2018-05-05 16:30:00,Regular,37,"Everton - Southampton, 1 - 1","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1623': {'scoreET': 0, 'coachId': 8541, 'side...",Goodison Park,0,2500083
20,364,"May 5, 2018 at 4:00:00 PM GMT+2",2018-05-05 14:00:00,Regular,37,"AFC Bournemouth - Swansea City, 1 - 0","[{'refereeId': 385704, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 32573, 'si...",Vitality Stadium,1659,2500079
21,364,"May 5, 2018 at 4:00:00 PM GMT+2",2018-05-05 14:00:00,Regular,37,"Leicester City - West Ham United, 0 - 2","[{'refereeId': 385737, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1631': {'scoreET': 0, 'coachId': 209010, 'si...",King Power Stadium,1633,2500084
22,364,"May 5, 2018 at 4:00:00 PM GMT+2",2018-05-05 14:00:00,Regular,37,"Watford - Newcastle United, 2 - 1","[{'refereeId': 388333, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 93112, 'sid...",Vicarage Road Stadium,1644,2500087
23,364,"May 5, 2018 at 4:00:00 PM GMT+2",2018-05-05 14:00:00,Regular,37,"West Bromwich Albion - Tottenham Hotspur, 1 - 0","[{'refereeId': 385916, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1627': {'scoreET': 0, 'coachId': 0, 'side': ...",The Hawthorns,1627,2500088
24,364,"May 5, 2018 at 1:30:00 PM GMT+2",2018-05-05 11:30:00,Regular,37,"Stoke City - Crystal Palace, 1 - 2","[{'refereeId': 384888, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1639': {'scoreET': 0, 'coachId': 8329, 'side...",Bet365 Stadium,1628,2500086
25,364,"May 4, 2018 at 9:00:00 PM GMT+2",2018-05-04 19:00:00,Regular,37,"Brighton & Hove Albion - Manchester United, 1 - 0","[{'refereeId': 378951, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",The American Express Community Stadium,1651,2500081
26,364,"April 30, 2018 at 9:00:00 PM GMT+2",2018-04-30 19:00:00,Regular,36,"Tottenham Hotspur - Watford, 2 - 0","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 93112, 'sid...",Wembley Stadium,1624,2500077
27,364,"April 29, 2018 at 5:30:00 PM GMT+2",2018-04-29 15:30:00,Regular,36,"Manchester United - Arsenal, 2 - 1","[{'refereeId': 385704, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",Old Trafford,1611,2500073
28,364,"April 29, 2018 at 3:15:00 PM GMT+2",2018-04-29 13:15:00,Regular,36,"West Ham United - Manchester City, 1 - 4","[{'refereeId': 385915, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1633': {'scoreET': 0, 'coachId': 8235, 'side...",London Stadium,1625,2500078
29,364,"April 28, 2018 at 6:30:00 PM GMT+2",2018-04-28 16:30:00,Regular,36,"Swansea City - Chelsea, 0 - 1","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 0, 'side':...",Liberty Stadium,1610,2500076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,364,"August 27, 2017 at 5:00:00 PM GMT+2",2017-08-27 15:00:00,Regular,3,"Liverpool - Arsenal, 4 - 0","[{'refereeId': 384888, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",Anfield,1612,2499743
351,364,"August 27, 2017 at 5:00:00 PM GMT+2",2017-08-27 15:00:00,Regular,3,"Tottenham Hotspur - Burnley, 1 - 1","[{'refereeId': 381853, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",Wembley Stadium,0,2499746
352,364,"August 27, 2017 at 2:30:00 PM GMT+2",2017-08-27 12:30:00,Regular,3,"Chelsea - Everton, 2 - 0","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1623': {'scoreET': 0, 'coachId': 268779, 'si...",Stamford Bridge,1610,2499740
353,364,"August 27, 2017 at 2:30:00 PM GMT+2",2017-08-27 12:30:00,Regular,3,"West Bromwich Albion - Stoke City, 1 - 1","[{'refereeId': 378952, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1639': {'scoreET': 0, 'coachId': 9054, 'side...",The Hawthorns,0,2499748
354,364,"August 26, 2017 at 6:30:00 PM GMT+2",2017-08-26 16:30:00,Regular,3,"Manchester United - Leicester City, 2 - 0","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1631': {'scoreET': 0, 'coachId': 333782, 'si...",Old Trafford,1611,2499744
355,364,"August 26, 2017 at 4:00:00 PM GMT+2",2017-08-26 14:00:00,Regular,3,"Crystal Palace - Swansea City, 0 - 2","[{'refereeId': 385911, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 381291, 's...",Selhurst Park,10531,2499741
356,364,"August 26, 2017 at 4:00:00 PM GMT+2",2017-08-26 14:00:00,Regular,3,"Huddersfield Town - Southampton, 0 - 0","[{'refereeId': 385912, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1673': {'scoreET': 0, 'coachId': 18572, 'sid...",The John Smith's Stadium,0,2499742
357,364,"August 26, 2017 at 4:00:00 PM GMT+2",2017-08-26 14:00:00,Regular,3,"Newcastle United - West Ham United, 3 - 0","[{'refereeId': 385915, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1633': {'scoreET': 0, 'coachId': 269869, 'si...",St. James' Park,1613,2499745
358,364,"August 26, 2017 at 4:00:00 PM GMT+2",2017-08-26 14:00:00,Regular,3,"Watford - Brighton & Hove Albion, 0 - 0","[{'refereeId': 408156, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 71037, 'sid...",Vicarage Road Stadium,0,2499747
359,364,"August 26, 2017 at 1:30:00 PM GMT+2",2017-08-26 11:30:00,Regular,3,"AFC Bournemouth - Manchester City, 1 - 2","[{'refereeId': 385909, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1659': {'scoreET': 0, 'coachId': 8934, 'side...",Vitality Stadium,1625,2499739
360,364,"August 21, 2017 at 9:00:00 PM GMT+2",2017-08-21 19:00:00,Regular,2,"Manchester City - Everton, 1 - 1","[{'refereeId': 379443, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1623': {'scoreET': 0, 'coachId': 268779, 'si...",Etihad Stadium,0,2499734
361,364,"August 20, 2017 at 5:00:00 PM GMT+2",2017-08-20 15:00:00,Regular,2,"Tottenham Hotspur - Chelsea, 1 - 2","[{'refereeId': 378952, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1610': {'scoreET': 0, 'coachId': 272869, 'si...",Wembley Stadium,1610,2499737
362,364,"August 20, 2017 at 2:30:00 PM GMT+2",2017-08-20 12:30:00,Regular,2,"Huddersfield Town - Newcastle United, 1 - 0","[{'refereeId': 378951, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1613': {'scoreET': 0, 'coachId': 210700, 'si...",The John Smith's Stadium,1673,2499731
363,364,"August 19, 2017 at 6:30:00 PM GMT+2",2017-08-19 16:30:00,Regular,2,"Stoke City - Arsenal, 1 - 0","[{'refereeId': 385911, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",Bet365 Stadium,1639,2499735
364,364,"August 19, 2017 at 4:00:00 PM GMT+2",2017-08-19 14:00:00,Regular,2,"AFC Bournemouth - Watford, 0 - 2","[{'refereeId': 388333, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 71037, 'sid...",Vitality Stadium,1644,2499729
365,364,"August 19, 2017 at 4:00:00 PM GMT+2",2017-08-19 14:00:00,Regular,2,"Burnley - West Bromwich Albion, 0 - 1","[{'refereeId': 384888, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",Turf Moor,1627,2499730
366,364,"August 19, 2017 at 4:00:00 PM GMT+2",2017-08-19 14:00:00,Regular,2,"Leicester City - Brighton & Hove Albion, 2 - 0","[{'refereeId': 381852, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1631': {'scoreET': 0, 'coachId': 333782, 'si...",King Power Stadium,1631,2499732
367,364,"August 19, 2017 at 4:00:00 PM GMT+2",2017-08-19 14:00:00,Regular,2,"Liverpool - Crystal Palace, 1 - 0","[{'refereeId': 385704, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1628': {'scoreET': 0, 'coachId': 268775, 'si...",Anfield,1612,2499733
368,364,"August 19, 2017 at 4:00:00 PM GMT+2",2017-08-19 14:00:00,Regular,2,"Southampton - West Ham United, 3 - 2","[{'refereeId': 381853, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1633': {'scoreET': 0, 'coachId': 269869, 'si...",St. Mary's Stadium,1619,2500036
369,364,"August 19, 2017 at 1:30:00 PM GMT+2",2017-08-19 11:30:00,Regular,2,"Swansea City - Manchester United, 0 - 4","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 381291, 's...",Liberty Stadium,1611,2499736
370,364,"August 13, 2017 at 5:00:00 PM GMT+2",2017-08-13 15:00:00,Regular,1,"Manchester United - West Ham United, 4 - 0","[{'refereeId': 384888, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1633': {'scoreET': 0, 'coachId': 269869, 'si...",Old Trafford,1611,2499724
371,364,"August 13, 2017 at 2:30:00 PM GMT+2",2017-08-13 12:30:00,Regular,1,"Newcastle United - Tottenham Hotspur, 0 - 2","[{'refereeId': 385911, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1613': {'scoreET': 0, 'coachId': 210700, 'si...",St. James' Park,1624,2499725
372,364,"August 12, 2017 at 6:30:00 PM GMT+2",2017-08-12 16:30:00,Regular,1,"Brighton & Hove Albion - Manchester City, 0 - 2","[{'refereeId': 384965, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",The American Express Community Stadium,1625,2499720
373,364,"August 12, 2017 at 4:00:00 PM GMT+2",2017-08-12 14:00:00,Regular,1,"Chelsea - Burnley, 2 - 3","[{'refereeId': 378951, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",Stamford Bridge,1646,2499721
374,364,"August 12, 2017 at 4:00:00 PM GMT+2",2017-08-12 14:00:00,Regular,1,"Crystal Palace - Huddersfield Town, 0 - 3","[{'refereeId': 381851, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1628': {'scoreET': 0, 'coachId': 268775, 'si...",Selhurst Park,1673,2499722
375,364,"August 12, 2017 at 4:00:00 PM GMT+2",2017-08-12 14:00:00,Regular,1,"Everton - Stoke City, 1 - 0","[{'refereeId': 385915, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1623': {'scoreET': 0, 'coachId': 268779, 'si...",Goodison Park,1623,2499723
376,364,"August 12, 2017 at 4:00:00 PM GMT+2",2017-08-12 14:00:00,Regular,1,"Southampton - Swansea City, 0 - 0","[{'refereeId': 385916, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'10531': {'scoreET': 0, 'coachId': 381291, 's...",St. Mary's Stadium,0,2499726
377,364,"August 12, 2017 at 4:00:00 PM GMT+2",2017-08-12 14:00:00,Regular,1,"West Bromwich Albion - AFC Bournemouth, 1 - 0","[{'refereeId': 379443, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1659': {'scoreET': 0, 'coachId': 8934, 'side...",The Hawthorns,1627,2499728
378,364,"August 12, 2017 at 1:30:00 PM GMT+2",2017-08-12 11:30:00,Regular,1,"Watford - Liverpool, 3 - 3","[{'refereeId': 378952, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1644': {'scoreET': 0, 'coachId': 71037, 'sid...",Vicarage Road Stadium,0,2499727
379,364,"August 11, 2017 at 8:45:00 PM GMT+2",2017-08-11 18:45:00,Regular,1,"Arsenal - Leicester City, 4 - 3","[{'refereeId': 385909, 'role': 'referee'}, {'r...",4405654,181150,Played,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",Emirates Stadium,1609,2499719

In [77]:
# 可以根据这个表的名字查出每个球队唯一的wyID，如Everton是1623
df_teams = pd.read_json('teams.json')
df_teams

,area,city,name,officialName,type,wyId
0,"{'name': 'England', 'id': '0', 'alpha3code': '...",Newcastle upon Tyne,Newcastle United,Newcastle United FC,club,1613
1,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Vigo,Celta de Vigo,Real Club Celta de Vigo,club,692
2,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Barcelona,Espanyol,Reial Club Deportiu Espanyol,club,691
3,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Vitoria-Gasteiz,Deportivo Alav\u00e9s,Deportivo Alav\u00e9s,club,696
4,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Valencia,Levante,Levante UD,club,695
5,"{'name': 'France', 'id': '250', 'alpha3code': ...",Troyes,Troyes,Esp\u00e9rance Sportive Troyes Aube Champagne,club,3795
6,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Getafe (Madrid),Getafe,Getafe Club de F\u00fatbol,club,698
7,"{'name': 'Germany', 'id': '276', 'alpha3code':...",M\u00f6nchengladbach,Borussia M'gladbach,Borussia VfL M\u00f6nchengladbach,club,2454
8,"{'name': 'England', 'id': '0', 'alpha3code': '...","Huddersfield, West Yorkshire",Huddersfield Town,Huddersfield Town FC,club,1673
9,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Bilbao,Athletic Club,Athletic Club Bilbao,club,678
10,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Madrid,Atl\u00e9tico Madrid,Club Atl\u00e9tico de Madrid,club,679
11,"{'name': 'France', 'id': '250', 'alpha3code': ...",Lyon,Olympique Lyonnais,Olympique Lyonnais,club,3766
12,"{'name': 'France', 'id': '250', 'alpha3code': ...",Paris,PSG,Paris Saint-Germain FC,club,3767
13,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Valencia,Valencia,Valencia Club de F\u00fatbol,club,674
14,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Madrid,Real Madrid,Real Madrid Club de F\u00fatbol,club,675
15,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Barcelona,Barcelona,FC Barcelona,club,676
16,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Las Palmas de Gran Canaria,Las Palmas,UD Las Palmas,club,714
17,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Legan\u00e9s,Legan\u00e9s,CD Legan\u00e9s,club,712
18,"{'name': 'Italy', 'id': '380', 'alpha3code': '...",Ferrara,SPAL,Societ\u00e0 Polisportiva Ars et Labor 2013,club,3204
19,"{'name': 'Wales', 'id': '0', 'alpha3code': 'XW...",Swansea,Swansea City,Swansea City AFC,club,10531
20,"{'name': 'France', 'id': '250', 'alpha3code': ...",Marseille,Olympique Marseille,Olympique de Marseille,club,3771
21,"{'name': 'France', 'id': '250', 'alpha3code': ...",La Chapelle-sur-Erdre,Nantes,FC Nantes,club,3770
22,"{'name': 'France', 'id': '250', 'alpha3code': ...",Nice,Nice,O.G.C. Nice C\u00f4te d'Azur,club,3775
23,"{'name': 'France', 'id': '250', 'alpha3code': ...",Rennes,Rennes,Stade Rennais FC,club,3774
24,"{'name': 'France', 'id': '250', 'alpha3code': ...",Strasbourg,Strasbourg,RC Strasbourg Alsace,club,3779
25,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",Eibar,Eibar,SD Eibar,club,701
26,"{'name': 'England', 'id': '0', 'alpha3code': '...","Bournemouth, Dorset",AFC Bournemouth,AFC Bournemouth,club,1659
27,"{'name': 'England', 'id': '0', 'alpha3code': '...","Brighton, East Sussex",Brighton & Hove Albion,Brighton & Hove Albion FC,club,1651
28,"{'name': 'Germany', 'id': '276', 'alpha3code':...",Bremen,Werder Bremen,SV Werder Bremen,club,2443
29,"{'name': 'Germany', 'id': '276', 'alpha3code':...",Leverkusen,Bayer Leverkusen,TSV Bayer 04 Leverkusen,club,2446
...,...,...,...,...,...,...
112,"{'name': 'Panama', 'id': 591, 'alpha3code': 'P...",Ciudad de Panam\u00e1,Panama,Panama,national,17929
113,"{'name': 'Australia', 'id': 36, 'alpha3code': ...",Sydney,Australia,Australia,national,8493
114,"{'name': 'Argentina', 'id': 32, 'alpha3code': ...","Buenos Aires, Ciudad de Buenos Aires",Argentina,Argentina,national,12274
115,"{'name': 'Northern Ireland', 'id': 0, 'alpha3c...",Belfast,Northern Ireland,Northern Ireland,national,10962
116,"{'name': 'Portugal', 'id': 620, 'alpha3code': ...",Lisboa,Portugal,Portugal,national,9905
117,"{'name': 'Belgium', 'id': 56, 'alpha3code': 'B...",Bruxelles (Brussel),Belgium,Belgium,national,5629
118,"{'name': 'Denmark', 'id': 208, 'alpha3code': '...",Br\u00f8ndby,Denmark,Denmark,national,7712
119,"{'name': 'Uruguay', 'id': 858, 'alpha3code': '...",Montevideo,Uruguay,Uruguay,national,15670
120,"{'name': 'Wales', 'id': 0, 'alpha3code': 'XWA'...",Cardiff,Wales,Wales,national,10682
121,"{'name': 'Costa Rica', 'id': 188, 'alpha3code'...",San Jos\u00e9,Costa Rica,Costa Rica,national,16871
122,"{'name': 'England', 'id': 0, 'alpha3code': 'XE...",London,England,England,national,2413
123,"{'name': 'Egypt', 'id': 818, 'alpha3code': 'EG...",Cairo,Egypt,Egypt,national,16129
124,"{'name': 'Japan', 'id': 392, 'alpha3code': 'JP...",T\u014dky\u014d (Tokyo),Japan,Japan,national,12913
125,"{'name': 'Iran', 'id': 364, 'alpha3code': 'IRN...",Tehr\u0101n (Teheran),Iran,Iran,national,10840
126,"{'name': 'Austria', 'id': 40, 'alpha3code': 'A...",Wien,Austria,Austria,national,9109
127,"{'name': 'Iceland', 'id': 352, 'alpha3code': '...",Reykjav\u00edk,Iceland,Iceland,national,7839
128,"{'name': 'Croatia', 'id': 191, 'alpha3code': '...",Zagreb,Croatia,Croatia,national,9598
129,"{'name': 'Mexico', 'id': 484, 'alpha3code': 'M...","Coyoac\u00e1n, Ciudad de M\u00e9xico (D.F.)",Mexico,Mexico,national,15473
130,"{'name': 'Ireland Republic', 'id': 372, 'alpha...",Dublin,Republic of Ireland,Republic of Ireland,national,8274
131,"{'name': 'Czech Republic', 'id': 203, 'alpha3c...",Praha,Czech Republic,Czech Republic,national,11555
132,"{'name': 'Senegal', 'id': 686, 'alpha3code': '...",Dakar,Senegal,Senegal,national,19314
133,"{'name': 'Italy', 'id': 380, 'alpha3code': 'IT...",Roma,Italy,Italy,national,3757
134,"{'name': 'Peru', 'id': 604, 'alpha3code': 'PER...",Lima,Peru,Peru,national,15594
135,"{'name': 'France', 'id': 250, 'alpha3code': 'F...",Paris,France,France,national,4418
136,"{'name': 'Saudi Arabia', 'id': 682, 'alpha3cod...",Ar-Riy\u0101\u1e0d (Riyadh),Saudi Arabia,Saudi Arabia,national,16521
137,"{'name': 'Spain', 'id': 724, 'alpha3code': 'ES...",Las Rozas,Spain,Spain,national,1598
138,"{'name': 'Serbia', 'id': 688, 'alpha3code': 'S...",Beograd,Serbia,Serbia,national,17322
139,"{'name': 'Switzerland', 'id': 756, 'alpha3code...",Bern,Switzerland,Switzerland,national,6697
140,"{'name': 'Poland', 'id': 616, 'alpha3code': 'P...",Warszawa,Poland,Poland,national,13869
141,"{'name': 'Nigeria', 'id': 566, 'alpha3code': '...",Abuja,Nigeria,Nigeria,national,16823

In [129]:
teamId_dic = {}
for i in range(len(df_matches_Eng)):
    for teamId in df_matches_Eng['teamsData'][i].keys():
        if teamId not in teamId_dic:
            teamId_dic[teamId] = 0
            
for i in range(len(df_matches_Eng)):
    if df_matches_Eng['winner'][i] == 0:
        team0 = list(df_matches_Eng['teamsData'][i].keys())[0]
        team1 = list(df_matches_Eng['teamsData'][i].keys())[1]
        teamId_dic[team0] += 1
        teamId_dic[team1] += 1
    else:
        teamId_dic[str(df_matches_Eng['winner'][i])] += 3
team_ranking = sorted(teamId_dic.items(), key=lambda x:x[1], reverse=True)
# Name:id
Name_teamId_matchesId = {}
for index, value in enumerate(team_ranking):
    print(index+1, df_teams[df_teams['wyId']==int(team_ranking[index][0])]['name'].values[0],team_ranking[index][1])
    Name_teamId_matchesId[df_teams[df_teams['wyId']==int(team_ranking[index][0])]['name'].values[0]] = {'teamId':team_ranking[index][0], 'matchesId':[]}
for i in range(len(df_matches_Eng)):
    team0_id = list(df_matches_Eng['teamsData'][i].keys())[0]
    team1_id = list(df_matches_Eng['teamsData'][i].keys())[1]
    for key, value in Name_teamId_matchesId.items():
        if team0_id == value['teamId']:
            value['matchesId'].append(df_matches_Eng['wyId'][i])
        elif team1_id == value['teamId']:
            value['matchesId'].append(df_matches_Eng['wyId'][i])

1 Manchester City 100
2 Manchester United 81
3 Tottenham Hotspur 77
4 Liverpool 75
5 Chelsea 70
6 Arsenal 63
7 Burnley 54
8 Everton 48
9 Leicester City 47
10 AFC Bournemouth 44
11 Crystal Palace 44
12 Newcastle United 44
13 West Ham United 42
14 Brighton & Hove Albion 41
15 Watford 39
16 Huddersfield Town 37
17 Southampton 36
18 Swansea City 33
19 Stoke City 33
20 West Bromwich Albion 31

In [130]:
Name_teamId_matchesId

{'Manchester City': {'teamId': '1625',
  'matchesId': [2500095,
   2500024,
   2500085,
   2500078,
   2500065,
   2500057,
   2500045,
   2500033,
   2500016,
   2500004,
   2499990,
   2499982,
   2499972,
   2499966,
   2499954,
   2499943,
   2499934,
   2499921,
   2499915,
   2499904,
   2499895,
   2499881,
   2499873,
   2499865,
   2499857,
   2499841,
   2499834,
   2499822,
   2499818,
   2499802,
   2499794,
   2499781,
   2499774,
   2499767,
   2499754,
   2499739,
   2499734,
   2499720]},
 'Manchester United': {'teamId': '1611',
  'matchesId': [2500093,
   2500028,
   2500081,
   2500073,
   2500059,
   2500053,
   2500045,
   2500034,
   2500014,
   2500001,
   2499996,
   2499983,
   2499976,
   2499968,
   2499951,
   2499944,
   2499932,
   2499924,
   2499914,
   2499903,
   2499898,
   2499884,
   2499873,
   2499860,
   2499853,
   2499843,
   2499836,
   2499819,
   2499816,
   2499801,
   2499793,
   2499784,
   2499775,
   2499764,
   2499756,
   2499744,
   2499736,
   2499724]},
 'Tottenham Hotspur': {'teamId': '1624',
  'matchesId': [2500097,
   2500027,
   2500088,
   2500077,
   2500061,
   2500057,
   2500046,
   2500031,
   2500009,
   2500007,
   2499993,
   2499987,
   2499975,
   2499968,
   2499955,
   2499946,
   2499926,
   2499937,
   2499916,
   2499901,
   2499895,
   2499888,
   2499877,
   2499867,
   2499852,
   2499847,
   2499830,
   2499827,
   2499816,
   2499807,
   2499797,
   2499783,
   2499778,
   2499766,
   2499752,
   2499746,
   2499737,
   2499725]},
 'Liverpool': {'teamId': '1612',
  'matchesId': [2500092,
   2500082,
   2500072,
   2500068,
   2500052,
   2500043,
   2500032,
   2500023,
   2500014,
   2500003,
   2499995,
   2499984,
   2499975,
   2499959,
   2499957,
   2499943,
   2499931,
   2499923,
   2499913,
   2499899,
   2499889,
   2499887,
   2499872,
   2499861,
   2499858,
   2499842,
   2499835,
   2499828,
   2499815,
   2499807,
   2499793,
   2499785,
   2499773,
   2499763,
   2499754,
   2499743,
   2499733,
   2499727]},
 'Chelsea': {'teamId': '1610',
  'matchesId': [2500094,
   2500062,
   2500082,
   2500076,
   2500020,
   2500055,
   2500042,
   2500031,
   2500011,
   2500004,
   2499996,
   2499979,
   2499977,
   2499962,
   2499950,
   2499940,
   2499929,
   2499920,
   2499910,
   2499902,
   2499892,
   2499880,
   2499878,
   2499862,
   2499855,
   2499842,
   2499838,
   2499819,
   2499809,
   2499799,
   2499791,
   2499781,
   2499776,
   2499760,
   2499753,
   2499740,
   2499737,
   2499721]},
 'Arsenal': {'teamId': '1609',
  'matchesId': [2500091,
   2500022,
   2500080,
   2500073,
   2500060,
   2500054,
   2500040,
   2500029,
   2500010,
   2499999,
   2499990,
   2499987,
   2499970,
   2499960,
   2499949,
   2499939,
   2499929,
   2499928,
   2499911,
   2499899,
   2499890,
   2499882,
   2499875,
   2499860,
   2499850,
   2499839,
   2499830,
   2499822,
   2499810,
   2499800,
   2499798,
   2499780,
   2499769,
   2499760,
   2499749,
   2499743,
   2499735,
   2499719]},
 'Burnley': {'teamId': '1646',
  'matchesId': [2500089,
   2500080,
   2500069,
   2500066,
   2500020,
   2500049,
   2500047,
   2500038,
   2500018,
   2500000,
   2499992,
   2499986,
   2499972,
   2499964,
   2499951,
   2499941,
   2499931,
   2499922,
   2499914,
   2499901,
   2499891,
   2499879,
   2499869,
   2499864,
   2499849,
   2499839,
   2499832,
   2499824,
   2499812,
   2499802,
   2499790,
   2499782,
   2499771,
   2499763,
   2499751,
   2499746,
   2499730,
   2499721]},
 'Everton': {'teamId': '1623',
  'matchesId': [2500098,
   2500083,
   2500071,
   2500063,
   2500056,
   2500043,
   2500033,
   2500025,
   2500012,
   2500000,
   2499997,
   2499980,
   2499970,
   2499963,
   2499952,
   2499946,
   2499932,
   2499919,
   2499918,
   2499902,
   2499893,
   2499885,
   2499872,
   2499863,
   2499856,
   2499845,
   2499833,
   2499820,
   2499814,
   2499800,
   2499789,
   2499782,
   2499772,
   2499764,
   2499752,
   2499740,
   2499734,
   2499723]},
 'Leicester City': {'teamId': '1631',
  'matchesId': [2500097,
   2500022,
   2500084,
   2500070,
   2500064,
   2500049,
   2500044,
   2500030,
   2500017,
   2500002,
   2499994,
   2499982,
   2499974,
   2499963,
   2499953,
   2499940,
   2499933,
   2499923,
   2499917,
   2499903,
   2499894,
   2499886,
   2499874,
   2499864,
   2499852,
   2499848,
   2499834,
   2499825,
   2499814,
   2499806,
   2499792,
   2499779,
   2499773,
   2499762,
   2499753,
   2499744,
   2499732,
   2499719]},
 'AFC Bournemouth': {'teamId': '1659',
  'matchesId': [2500089,
   2500079,
   2500075,
   2500059,
   2500052,
   2500039,
   2500037,
   2500019,
   2500009,
   2500002,
   2499989,
   2499981,
   2499969,
   2499962,
   2499958,
   2499939,
   2499930,
   2499919,
   2499909,
   2499904,
   2499889,
   2499884,
   2499870,
   2499859,
   2499849,
   2499846,
   2499829,
   2499823,
   2499809,
   2499805,
   2499797,
   2499779,
   2499772,
   2499759,
   2499749,
   2499739,
   2499729,
   2499728]},
 'Crystal Palace': {'teamId': '1628',
  'matchesId': [2500090,
   2500086,
   2500070,
   2500067,
   2500050,
   2500039,
   2500032,
   2500021,
   2500011,
   2500001,
   2499993,
   2499980,
   2499973,
   2499961,
   2499949,
   2499941,
   2499935,
   2499921,
   2499911,
   2499907,
   2499894,
   2499883,
   2499870,
   2499868,
   2499851,
   2499840,
   2499833,
   2499827,
   2499813,
   2499803,
   2499791,
   2499784,
   2499774,
   2499761,
   2499751,
   2499741,
   2499733,
   2499722]},
 'Newcastle United': {'teamId': '1613',
  'matchesId': [2500094,
   2500027,
   2500087,
   2500074,
   2500063,
   2500054,
   2500044,
   2500035,
   2500015,
   2500003,
   2499989,
   2499983,
   2499973,
   2499964,
   2499954,
   2499945,
   2499936,
   2499925,
   2499915,
   2499908,
   2499890,
   2499885,
   2499874,
   2499862,
   2499854,
   2499844,
   2499836,
   2499823,
   2499812,
   2499803,
   2499795,
   2499785,
   2499770,
   2499765,
   2499757,
   2499745,
   2499731,
   2499725]},
 'West Ham United': {'teamId': '1633',
  'matchesId': [2500098,
   2500028,
   2500084,
   2500078,
   2500060,
   2500058,
   2500042,
   2499738,
   2500018,
   2500006,
   2499995,
   2499988,
   2499971,
   2499961,
   2499958,
   2499942,
   2499926,
   2499938,
   2499909,
   2499908,
   2499896,
   2499882,
   2499878,
   2499865,
   2499856,
   2499848,
   2499837,
   2499828,
   2499813,
   2499808,
   2499790,
   2499788,
   2499778,
   2499768,
   2499758,
   2499745,
   2500036,
   2499724]},
 'Brighton & Hove Albion': {'teamId': '1651',
  'matchesId': [2500092,
   2500024,
   2500081,
   2500069,
   2500061,
   2500050,
   2500041,
   2500030,
   2500012,
   2499999,
   2499991,
   2499985,
   2499971,
   2499965,
   2499950,
   2499948,
   2499930,
   2499925,
   2499910,
   2499900,
   2499891,
   2499888,
   2499871,
   2499861,
   2499851,
   2499843,
   2499831,
   2499826,
   2499811,
   2499808,
   2499789,
   2499780,
   2499770,
   2499759,
   2499750,
   2499747,
   2499732,
   2499720]},
 'Watford': {'teamId': '1644',
  'matchesId': [2500093,
   2500087,
   2500077,
   2500067,
   2500051,
   2500047,
   2500037,
   2500023,
   2500010,
   2500008,
   2499997,
   2499988,
   2499977,
   2499967,
   2499953,
   2499947,
   2499934,
   2499927,
   2499917,
   2499900,
   2499897,
   2499883,
   2499869,
   2499867,
   2499853,
   2499844,
   2499837,
   2499820,
   2499817,
   2499799,
   2499798,
   2499787,
   2499777,
   2499767,
   2499755,
   2499747,
   2499729,
   2499727]},
 'Huddersfield Town': {'teamId': '1673',
  'matchesId': [2500091,
   2500062,
   2500085,
   2500071,
   2500051,
   2500041,
   2500035,
   2500021,
   2500013,
   2500007,
   2499998,
   2499981,
   2499976,
   2499959,
   2499956,
   2499942,
   2499933,
   2499922,
   2499912,
   2499905,
   2499897,
   2499880,
   2499871,
   2499863,
   2499850,
   2499841,
   2499829,
   2499821,
   2499815,
   2499801,
   2499796,
   2499783,
   2499771,
   2499762,
   2499758,
   2499742,
   2499731,
   2499722]},
 'Southampton': {'teamId': '1619',
  'matchesId': [2500095,
   2500026,
   2500083,
   2500075,
   2500064,
   2500055,
   2500040,
   2499738,
   2500015,
   2500005,
   2499992,
   2499984,
   2499978,
   2499965,
   2499955,
   2499947,
   2499935,
   2499924,
   2499916,
   2499905,
   2499892,
   2499886,
   2499875,
   2499859,
   2499857,
   2499845,
   2499835,
   2499824,
   2499811,
   2499804,
   2499795,
   2499786,
   2499775,
   2499761,
   2499755,
   2499742,
   2500036,
   2499726]},
 'Swansea City': {'teamId': '10531',
  'matchesId': [2500096,
   2500026,
   2500079,
   2500076,
   2500065,
   2500056,
   2500048,
   2500034,
   2500013,
   2500006,
   2499991,
   2499986,
   2499974,
   2499960,
   2499957,
   2499945,
   2499937,
   2499927,
   2499913,
   2499907,
   2499893,
   2499881,
   2499876,
   2499866,
   2499855,
   2499846,
   2499832,
   2499826,
   2499810,
   2499806,
   2499796,
   2499788,
   2499777,
   2499766,
   2499757,
   2499741,
   2499736,
   2499726]},
 'Stoke City': {'teamId': '1639',
  'matchesId': [2500096,
   2500086,
   2500072,
   2500066,
   2500058,
   2500046,
   2500029,
   2500025,
   2500016,
   2500005,
   2499994,
   2499985,
   2499969,
   2499967,
   2499956,
   2499944,
   2499936,
   2499920,
   2499912,
   2499906,
   2499896,
   2499879,
   2499877,
   2499866,
   2499858,
   2499840,
   2499831,
   2499825,
   2499817,
   2499805,
   2499794,
   2499786,
   2499776,
   2499765,
   2499756,
   2499748,
   2499735,
   2499723]},
 'West Bromwich Albion': {'teamId': '1627',
  'matchesId': [2500090,
   2500088,
   2500074,
   2500068,
   2500053,
   2500048,
   2500038,
   2500019,
   2500017,
   2500008,
   2499998,
   2499979,
   2499978,
   2499966,
   2499952,
   2499948,
   2499938,
   2499928,
   2499918,
   2499906,
   2499898,
   2499887,
   2499876,
   2499868,
   2499854,
   2499847,
   2499838,
   2499821,
   2499818,
   2499804,
   2499792,
   2499787,
   2499769,
   2499768,
   2499750,
   2499748,
   2499730,
   2499728]}}

In [58]:
df_events_Eng = pd.read_json('events/events_England.json')
# Everton所有的动作
df_events_Eng[df_events_Eng['teamId']==1623]

,eventId,eventName,eventSec,id,matchId,matchPeriod,playerId,positions,subEventId,subEventName,tags,teamId
6453,3,Free Kick,31.174681,178214455,2499723,1H,10131,"[{'y': 0, 'x': 0}, {'y': 89, 'x': 66}]",34,Goal kick,[],1623
6455,1,Duel,33.812965,178214456,2499723,1H,293687,"[{'y': 89, 'x': 66}, {'y': 100, 'x': 78}]",10,Air duel,"[{'id': 702}, {'id': 1801}]",1623
6458,8,Pass,46.323501,178214457,2499723,1H,7919,"[{'y': 97, 'x': 34}, {'y': 95, 'x': 59}]",82,Head pass,[{'id': 1801}],1623
6459,1,Duel,47.004714,178214458,2499723,1H,293687,"[{'y': 95, 'x': 59}, {'y': 94, 'x': 64}]",13,Ground loose ball duel,"[{'id': 701}, {'id': 1802}]",1623
6462,8,Pass,49.880983,178214459,2499723,1H,293687,"[{'y': 95, 'x': 55}, {'y': 93, 'x': 57}]",82,Head pass,[{'id': 1801}],1623
6464,1,Duel,50.109404,178216502,2499723,1H,0,"[{'y': 93, 'x': 57}, {'y': 89, 'x': 53}]",13,Ground loose ball duel,"[{'id': 703}, {'id': 1801}]",1623
6465,8,Pass,51.022546,178214460,2499723,1H,25706,"[{'y': 89, 'x': 53}, {'y': 91, 'x': 69}]",85,Simple pass,[{'id': 1801}],1623
6466,8,Pass,51.624604,178214461,2499723,1H,7944,"[{'y': 91, 'x': 69}, {'y': 100, 'x': 75}]",85,Simple pass,[{'id': 1802}],1623
6470,3,Free Kick,85.962263,178214473,2499723,1H,293687,"[{'y': 100, 'x': 65}, {'y': 84, 'x': 81}]",36,Throw in,[{'id': 1802}],1623
6474,1,Duel,96.945738,178214477,2499723,1H,77546,"[{'y': 56, 'x': 33}, {'y': 55, 'x': 42}]",10,Air duel,"[{'id': 703}, {'id': 1801}]",1623
6475,8,Pass,98.265191,178214479,2499723,1H,56,"[{'y': 55, 'x': 42}, {'y': 54, 'x': 36}]",85,Simple pass,[{'id': 1801}],1623
6476,8,Pass,99.398625,178214481,2499723,1H,8143,"[{'y': 54, 'x': 36}, {'y': 63, 'x': 36}]",85,Simple pass,[{'id': 1802}],1623
6478,8,Pass,103.356274,178214483,2499723,1H,7919,"[{'y': 95, 'x': 30}, {'y': 97, 'x': 72}]",83,High pass,[{'id': 1801}],1623
6480,1,Duel,106.139608,178214490,2499723,1H,293687,"[{'y': 97, 'x': 72}, {'y': 93, 'x': 61}]",10,Air duel,"[{'id': 703}, {'id': 1801}]",1623
6482,7,Others on the ball,108.290691,178214492,2499723,1H,293687,"[{'y': 98, 'x': 73}, {'y': 89, 'x': 70}]",72,Touch,[],1623
6487,7,Others on the ball,116.880164,178214494,2499723,1H,293687,"[{'y': 98, 'x': 65}, {'y': 100, 'x': 66}]",72,Touch,[{'id': 1401}],1623
6490,8,Pass,130.656530,178214499,2499723,1H,7919,"[{'y': 91, 'x': 34}, {'y': 97, 'x': 52}]",82,Head pass,"[{'id': 1401}, {'id': 1802}]",1623
6491,1,Duel,134.603958,178214502,2499723,1H,293687,"[{'y': 97, 'x': 52}, {'y': 100, 'x': 47}]",12,Ground defending duel,"[{'id': 702}, {'id': 1801}]",1623
6498,8,Pass,161.221470,178214508,2499723,1H,7919,"[{'y': 65, 'x': 14}, {'y': 50, 'x': 11}]",85,Simple pass,"[{'id': 1401}, {'id': 1801}]",1623
6499,8,Pass,164.626056,178214510,2499723,1H,10131,"[{'y': 50, 'x': 11}, {'y': 45, 'x': 5}]",81,Hand pass,[{'id': 1801}],1623
6500,8,Pass,169.314197,178214511,2499723,1H,10131,"[{'y': 45, 'x': 5}, {'y': 89, 'x': 47}]",84,Launch,[{'id': 1801}],1623
6502,1,Duel,171.937730,178216504,2499723,1H,0,"[{'y': 89, 'x': 47}, {'y': 82, 'x': 9}]",10,Air duel,"[{'id': 701}, {'id': 1802}]",1623
6503,8,Pass,176.839196,178214513,2499723,1H,10131,"[{'y': 82, 'x': 9}, {'y': 91, 'x': 62}]",84,Launch,[{'id': 1801}],1623
6505,1,Duel,180.832306,178214516,2499723,1H,293687,"[{'y': 91, 'x': 62}, {'y': 86, 'x': 41}]",10,Air duel,"[{'id': 701}, {'id': 1802}]",1623
6506,7,Others on the ball,183.458434,178214521,2499723,1H,8143,"[{'y': 86, 'x': 41}, {'y': 90, 'x': 35}]",72,Touch,[{'id': 1401}],1623
6507,1,Duel,183.987009,178214525,2499723,1H,7919,"[{'y': 90, 'x': 35}, {'y': 94, 'x': 28}]",13,Ground loose ball duel,"[{'id': 703}, {'id': 1801}]",1623
6509,7,Others on the ball,188.328112,178214529,2499723,1H,7919,"[{'y': 94, 'x': 28}, {'y': 90, 'x': 32}]",72,Touch,[],1623
6511,1,Duel,190.329509,178214530,2499723,1H,7919,"[{'y': 90, 'x': 32}, {'y': 100, 'x': 25}]",12,Ground defending duel,"[{'id': 702}, {'id': 1801}]",1623
6513,3,Free Kick,201.192228,178214533,2499723,1H,7919,"[{'y': 100, 'x': 25}, {'y': 95, 'x': 39}]",36,Throw in,[{'id': 1801}],1623
6514,1,Duel,203.183570,178214534,2499723,1H,7944,"[{'y': 95, 'x': 39}, {'y': 95, 'x': 44}]",11,Ground attacking duel,"[{'id': 701}, {'id': 1802}]",1623
...,...,...,...,...,...,...,...,...,...,...,...,...
643082,8,Pass,2608.738032,251596375,2500098,2H,8240,"[{'y': 86, 'x': 24}, {'y': 89, 'x': 34}]",85,Simple pass,"[{'id': 1401}, {'id': 1801}]",1623
643084,1,Duel,2610.931505,251596376,2500098,2H,9194,"[{'y': 89, 'x': 34}, {'y': 99, 'x': 41}]",11,Ground attacking duel,"[{'id': 703}, {'id': 1801}]",1623
643085,8,Pass,2614.478054,251596378,2500098,2H,9194,"[{'y': 99, 'x': 41}, {'y': 69, 'x': 66}]",86,Smart pass,[{'id': 1801}],1623
643086,8,Pass,2615.493725,251596379,2500098,2H,145692,"[{'y': 69, 'x': 66}, {'y': 85, 'x': 64}]",85,Simple pass,[{'id': 1801}],1623
643087,8,Pass,2616.871291,251596380,2500098,2H,56,"[{'y': 85, 'x': 64}, {'y': 10, 'x': 69}]",83,High pass,[{'id': 1801}],1623
643088,8,Pass,2625.882140,251596381,2500098,2H,8239,"[{'y': 10, 'x': 69}, {'y': 19, 'x': 69}]",85,Simple pass,[{'id': 1801}],1623
643089,8,Pass,2627.926967,251596382,2500098,2H,7879,"[{'y': 19, 'x': 69}, {'y': 3, 'x': 77}]",85,Simple pass,[{'id': 1801}],1623
643090,8,Pass,2629.434814,251596383,2500098,2H,8239,"[{'y': 3, 'x': 77}, {'y': 9, 'x': 63}]",85,Simple pass,[{'id': 1801}],1623
643091,8,Pass,2632.306060,251596384,2500098,2H,7879,"[{'y': 9, 'x': 63}, {'y': 45, 'x': 55}]",85,Simple pass,[{'id': 1801}],1623
643092,8,Pass,2636.681697,251596385,2500098,2H,7919,"[{'y': 45, 'x': 55}, {'y': 71, 'x': 64}]",85,Simple pass,[{'id': 1801}],1623
643093,8,Pass,2638.826239,251596386,2500098,2H,25706,"[{'y': 71, 'x': 64}, {'y': 91, 'x': 78}]",85,Simple pass,[{'id': 1801}],1623
643094,1,Duel,2641.278662,251596387,2500098,2H,9194,"[{'y': 91, 'x': 78}, {'y': 94, 'x': 86}]",11,Ground attacking duel,"[{'id': 501}, {'id': 703}, {'id': 1801}]",1623
643096,8,Pass,2642.981466,251596388,2500098,2H,9194,"[{'y': 94, 'x': 86}, {'y': 71, 'x': 88}]",80,Cross,"[{'id': 402}, {'id': 1802}]",1623
643098,1,Duel,2650.804223,251596390,2500098,2H,8245,"[{'y': 85, 'x': 38}, {'y': 82, 'x': 41}]",13,Ground loose ball duel,"[{'id': 703}, {'id': 1801}]",1623
643101,3,Free Kick,2665.580593,251596391,2500098,2H,0,"[{'y': 87, 'x': 40}, {'y': 80, 'x': 56}]",31,Free Kick,[{'id': 1801}],1623
643102,8,Pass,2668.905130,251596392,2500098,2H,25706,"[{'y': 80, 'x': 56}, {'y': 15, 'x': 66}]",83,High pass,[{'id': 1801}],1623
643103,8,Pass,2676.466810,251596393,2500098,2H,8239,"[{'y': 15, 'x': 66}, {'y': 23, 'x': 62}]",85,Simple pass,[{'id': 1801}],1623
643104,8,Pass,2679.856529,251596394,2500098,2H,7879,"[{'y': 23, 'x': 62}, {'y': 39, 'x': 66}]",85,Simple pass,[{'id': 1801}],1623
643105,8,Pass,2682.271344,251596395,2500098,2H,56,"[{'y': 39, 'x': 66}, {'y': 63, 'x': 63}]",85,Simple pass,[{'id': 1801}],1623
643106,8,Pass,2683.754085,251596396,2500098,2H,25706,"[{'y': 63, 'x': 63}, {'y': 55, 'x': 73}]",85,Simple pass,[{'id': 1801}],1623
643107,8,Pass,2684.747496,251596397,2500098,2H,145692,"[{'y': 55, 'x': 73}, {'y': 48, 'x': 69}]",85,Simple pass,[{'id': 1801}],1623
643108,7,Others on the ball,2685.673386,251596398,2500098,2H,56,"[{'y': 48, 'x': 69}, {'y': 12, 'x': 34}]",72,Touch,[],1623
643111,1,Duel,2705.607149,251596400,2500098,2H,7919,"[{'y': 6, 'x': 32}, {'y': 7, 'x': 30}]",12,Ground defending duel,"[{'id': 503}, {'id': 701}, {'id': 1802}]",1623
643114,1,Duel,2710.493239,251596404,2500098,2H,7919,"[{'y': 35, 'x': 7}, {'y': 34, 'x': 7}]",12,Ground defending duel,"[{'id': 701}, {'id': 1802}]",1623
643117,1,Duel,2712.941293,251596987,2500098,2H,0,"[{'y': 34, 'x': 7}, {'y': 28, 'x': 5}]",12,Ground defending duel,"[{'id': 502}, {'id': 701}, {'id': 1802}]",1623
643137,1,Duel,2769.548083,251596405,2500098,2H,56,"[{'y': 16, 'x': 38}, {'y': 17, 'x': 41}]",12,Ground defending duel,"[{'id': 701}, {'id': 1802}]",1623
643139,2,Foul,2771.985870,251596406,2500098,2H,56,"[{'y': 17, 'x': 41}, {'y': 16, 'x': 38}]",20,Foul,[],1623
643144,7,Others on the ball,2790.457942,251596408,2500098,2H,8239,"[{'y': 31, 'x': 2}, {'y': 32, 'x': 0}]",72,Touch,[{'id': 1401}],1623
643145,5,Interruption,2796.732525,251596409,2500098,2H,0,"[{'y': 32, 'x': 0}, {'y': 100, 'x': 100}]",50,Ball out of the field,[],1623
643147,1,Duel,2831.211419,251596410,2500098,2H,7919,"[{'y': 53, 'x': 12}, {'y': 50, 'x': 14}]",10,Air duel,"[{'id': 701}, {'id': 1802}]",1623

# 计算每个队的H-indicator数组

In [174]:
import pandas as pd
import numpy as np

def matchId_teamId_passing_table(matchId, teamId, df):
    player_dic = {}
    for i in range(len(df)):
        if df['playerId'][i] not in player_dic:
            player_dic[df['playerId'][i]] = 0
        else:
            player_dic[df['playerId'][i]] += 1
    return player_dic

def sub_pitch_passing_table(matchID, teamID, df):
    table = {(x,y):[0,0]for x in range(101) for y in range(101)}
    for i in range(len(df)):
        table[(df['positions'][i][0]['x'], df['positions'][i][0]['y'])][0] += 1
        table[(df['positions'][i][1]['x'], df['positions'][i][1]['y'])][1] += 1    
    return table

def H_indicator(matchID, teamID, df):
    w = len(df) * 2
    _matchId_teamId_passing_table = matchId_teamId_passing_table(matchID, teamId, df)
    #print(_matchId_teamId_passing_table)
    data = np.array([value for key, value in _matchId_teamId_passing_table.items()])
    mu_p = data.mean()
    sigma_p = np.sqrt(data.var())
    #print(sub_pitch_passing_table(matchID, teamID, df))
    data = np.array([value[0]+value[1] for key, value in sub_pitch_passing_table(matchID, teamID, df).items()])
    mu_z = data.mean()
    sigma_z = np.sqrt(data.var())
    #print(mu_p, sigma_p, mu_z, sigma_z)
    h = 5/(1/w+1/mu_p+1/sigma_p+1/mu_z+1/sigma_z)
    return h

def get_matchID_teamID_passing_events(matchID, teamID, df_events):
    df_events = df_events[df_events['teamId'] == teamID]
    df_events = df_events[df_events['matchId'] == matchID]
    df_events = df_events[df_events['eventName'] == 'Pass']
    df_events = df_events.reset_index(drop=True)
    return df_events

In [178]:
H_value = {}
for name, values in Name_teamId_matchesId.items():
    H_value[name] = []
    for i in range(38):
        tmp_matchId = values['matchesId'][i]
        tmp_teamId = values['teamId']
        #print(tmp_matchId, tmp_teamId)
        tmp_df = get_matchID_teamID_passing_events(int(tmp_matchId), int(tmp_teamId), df_events_Eng)
        #print(tmp_df)
        H_value[name].append(H_indicator(tmp_matchId, tmp_teamId, tmp_df))

In [179]:
H_value

{'Manchester City': [0.4530382795266375,
  0.6306317024507244,
  0.5438679481588765,
  0.6489833778073129,
  0.7488831110406224,
  0.3948026382304348,
  0.44733314421127307,
  0.7007363129355147,
  0.6220902966600793,
  0.7269952148923001,
  0.47820471823812544,
  0.5253045852242803,
  0.5177738149420672,
  0.5173993262208442,
  0.6042645559081349,
  0.4881283629180168,
  0.6360467031563176,
  0.4700975040442832,
  0.6056070394212062,
  0.6774124249597088,
  0.33614977046599087,
  0.6077719783139192,
  0.4418464347785318,
  0.5533768841312874,
  0.574967921507233,
  0.5490522290943278,
  0.5790494403805064,
  0.47075528920283566,
  0.6844255498481424,
  0.5922758377722929,
  0.6567441978830559,
  0.4919536481403172,
  0.5463062828676177,
  0.487482574530444,
  0.5499890261573035,
  0.4699313147444585,
  0.40892402023153257,
  0.5751948529375064],
 'Manchester United': [0.35488531309581495,
  0.446628522238946,
  0.5130846829648429,
  0.48205973570098903,
  0.42868925581365,
  0.5560501028227353,
  0.238440534557642,
  0.5574394451086242,
  0.20943812250677232,
  0.48277814130512314,
  0.33164736602677136,
  0.46784392571475253,
  0.5803437777204326,
  0.35792964861997495,
  0.3501337637196529,
  0.4587626618185632,
  0.4379785383530631,
  0.37885142741093136,
  0.4924538629247233,
  0.3453639023503084,
  0.4357672005099476,
  0.4295304074104279,
  0.2443666057820435,
  0.15449937221465623,
  0.26413741365745136,
  0.4387207082240559,
  0.48128010994826126,
  0.2937462566171686,
  0.3003761690928691,
  0.5649800013058247,
  0.267365538296978,
  0.43414595448327725,
  0.28112967108069564,
  0.3712282739042228,
  0.43862766832268374,
  0.5061267866834819,
  0.4453361708071605,
  0.36843306447625834],
 'Tottenham Hotspur': [0.34936831861174866,
  0.42758133894430544,
  0.4701366054647194,
  0.42860962865077895,
  0.48256133029262727,
  0.3507943507767167,
  0.41241364921847373,
  0.40459288278341937,
  0.4221296187148219,
  0.5968018466776496,
  0.4976937550786712,
  0.3855963595251506,
  0.44313637795566396,
  0.39552152346697883,
  0.36553242267448804,
  0.42993834283989335,
  0.5144422556812266,
  0.4990156378450171,
  0.370365666240467,
  0.39625335345498885,
  0.3012512407215037,
  0.5613923231141035,
  0.4866652580610097,
  0.32019328835997807,
  0.4258236673173509,
  0.5186539152667297,
  0.41507018887563396,
  0.4487347021602234,
  0.38527996160345923,
  0.2684502767842955,
  0.51515715977083,
  0.4221834407063875,
  0.3072643232323137,
  0.5776143587657185,
  0.3606916862115793,
  0.4450686894192723,
  0.4449743422513713,
  0.5316232335799922],
 'Liverpool': [0.5481984686207004,
  0.5737748601980778,
  0.47092092117685114,
  0.43597380068193364,
  0.4783489485128636,
  0.42449868564238485,
  0.5078764906602787,
  0.42818507194793914,
  0.4468163091141308,
  0.5679261196254978,
  0.5455803476137949,
  0.3747288916959268,
  0.2405494013631614,
  0.6794818840107242,
  0.5606581619361075,
  0.2816000916129086,
  0.39434659115345755,
  0.43051099708234497,
  0.4462914912364449,
  0.33191051816056466,
  0.5003930374254805,
  0.5329526957167807,
  0.554373731938867,
  0.5124790861695858,
  0.4216165986161226,
  0.4503878993079803,
  0.4251014827760062,
  0.3549234823486796,
  0.5703286485983203,
  0.48157977032957444,
  0.4503061974404939,
  0.4662722227216353,
  0.34802376152263054,
  0.49948527913644336,
  0.2892356262390205,
  0.37694130827069644,
  0.5287843891568589,
  0.35479312742214786],
 'Chelsea': [0.42924829221373856,
  0.6201038623342893,
  0.270655241171441,
  0.43241587549358634,
  0.46207170677206943,
  0.3949827834460229,
  0.4449795952599194,
  0.3635465127096826,
  0.4461729930443121,
  0.29547820682536896,
  0.412266793580373,
  0.4266047425875411,
  0.3808336686866045,
  0.4477258947428899,
  0.40878365434051706,
  0.37716006771435673,
  0.31969734530330496,
  0.49490368370806176,
  0.5110835250476694,
  0.5177226413215102,
  0.41519517949547935,
  0.5816558306537905,
  0.5146350803582462,
  0.5554125884391516,
  0.454677868703545,
  0.3891343345569591,
  0.46014816157906324,
  0.34253092962596116,
  0.49683576438534915,
  0.3433326349584997,
  0.42338381440597805,
  0.3131068524196272,
  0.4067177318088337,
  0.3907665556605072,
  0.39135201637989386,
  0.4387140046636295,
  0.20557463456344363,
  0.40588095638700744],
 'Arsenal': [0.3924014607648511,
  0.3542023344072254,
  0.5098965446192474,
  0.3381614158365071,
  0.46644252284827137,
  0.5236766571818648,
  0.527386452747597,
  0.4839033135536926,
  0.3799310549218853,
  0.44945519155097874,
  0.4030633323464268,
  0.38474083196947745,
  0.4121654904452287,
  0.6731971738180084,
  0.5843646919208698,
  0.4031418161940871,
  0.4506654438798766,
  0.48258785209349037,
  0.48457814808150657,
  0.3729626946881479,
  0.5663368674127655,
  0.5373151943811973,
  0.5691929147681769,
  0.5014391811303351,
  0.6032942468885072,
  0.47752037378657197,
  0.2960792345213555,
  0.3427753874305021,
  0.5983297726393968,
  0.46700258510919257,
  0.40911563212056884,
  0.5226552135746001,
  0.45458541377245876,
  0.3882747418878945,
  0.4445014720390012,
  0.40112144589727067,
  0.544868107355833,
  0.47035130454715807],
 'Burnley': [0.33176401187928095,
  0.29061802581778307,
  0.25094952797982956,
  0.3419526312444262,
  0.29620364933102433,
  0.21062283595415437,
  0.21837624274311704,
  0.35013238662937196,
  0.29330704448651335,
  0.31481852782306596,
  0.2813857332781893,
  0.25942625529242486,
  0.20779932819821847,
  0.2644870980058106,
  0.32626760635547214,
  0.2977378493222495,
  0.27547039040153537,
  0.2157446522025703,
  0.18301821626501347,
  0.262282155881627,
  0.26494160327844174,
  0.30218011811050904,
  0.28429380595190534,
  0.30051395201619413,
  0.26994311998351106,
  0.26390612186296025,
  0.2263813629852907,
  0.26183194779658764,
  0.35433106081614196,
  0.17726338918952958,
  0.3402269293469265,
  0.2298937731403119,
  0.34045271312181347,
  0.20288152630925452,
  0.19451314097078148,
  0.22661658361449893,
  0.36925879235575365,
  0.2439431834592876],
 'Everton': [0.27777631751732423,
  0.3128000474882103,
  0.3242110647120764,
  0.3720364893084819,
  0.3240695194244126,
  0.2558128990057794,
  0.15357312446848195,
  0.34224964611680425,
  0.32332928634747543,
  0.2632693127723746,
  0.2703318362358553,
  0.30029946119068657,
  0.2873402116868101,
  0.2693769941762691,
  0.3635098580474777,
  0.2774437260169878,
  0.28431401195305783,
  0.3643486768705311,
  0.26344113622761434,
  0.2598700011809462,
  0.3318027279042266,
  0.325046508867954,
  0.13453717240300403,
  0.27935109676088693,
  0.32904232648643633,
  0.2469418941234885,
  0.19824254514584094,
  0.232938379428127,
  0.36208264695981623,
  0.21965394213126938,
  0.3371138534204137,
  0.39260592517504656,
  0.3318401460649523,
  0.3718792375982117,
  0.3565869205716206,
  0.33608925136397005,
  0.22670376385217755,
  0.38129905352961274],
 'Leicester City': [0.20296563320723568,
  0.2558533143910848,
  0.3272602696998275,
  0.3059562558668273,
  0.3491980532451044,
  0.34142797326572505,
  0.4010438632638059,
  0.33768576209698875,
  0.35481699085455487,
  0.33685506549519484,
  0.3523706951778279,
  0.205475968283949,
  0.4071232533083804,
  0.342724705508353,
  0.3248825805617703,
  0.31429343495246037,
  0.3640223624713175,
  0.27173043052616713,
  0.2753467989641309,
  0.3394600816876987,
  0.34540789744816025,
  0.28163688424341304,
  0.41393991081252246,
  0.30669115637249217,
  0.25420773184942763,
  0.30721803051368246,
  0.18810173535767866,
  0.32279153348325723,
  0.24441814404057385,
  0.2944579104854129,
  0.37651039874996833,
  0.25462724141142784,
  0.2681519335864168,
  0.26220450441274745,
  0.27018381207837033,
  0.2133139769678462,
  0.3323951292216929,
  0.19103085730640684],
 'AFC Bournemouth': [0.30694070794989986,
  0.2780803695481905,
  0.3885546072966604,
  0.33643666304710373,
  0.29064429431129274,
  0.370047858126627,
  0.32112752073718404,
  0.4323728914834543,
  0.2471418219544878,
  0.27332180490329855,
  0.4243795760419845,
  0.3185749259731876,
  0.31325393690083364,
  0.2584647658645169,
  0.33338629026233907,
  0.2598196127117636,
  0.30936769541492315,
  0.30479838427483863,
  0.31912925555484567,
  0.17871688914657785,
  0.3809771571048214,
  0.333357120808329,
  0.329238131616244,
  0.3207487110329335,
  0.4418106002395337,
  0.36904844283187244,
  0.18545340533865945,
  0.29118955596909246,
  0.3574985058417334,
  0.2824809170268213,
  0.18771508133842646,
  0.40308120949020676,
  0.3181253675517849,
  0.48108903247548457,
  0.3094979322569713,
  0.18500005917316897,
  0.33502595640408234,
  0.46330715727056315],
 'Crystal Palace': [0.42221582744196373,
  0.30546142632070805,
  0.3238824721079377,
  0.25392709520125195,
  0.2820636842049762,
  0.3522122132359026,
  0.2419333081536061,
  0.2748667397668124,
  0.2733000098093782,
  0.20582073976094598,
  0.1523588538423551,
  0.2577556993379195,
  0.3257721136904506,
  0.3452248971016578,
  0.3266394794893733,
  0.22837847290236568,
  0.25718571038288346,
  0.1530257340612916,
  0.25226188920039333,
  0.25362374468695154,
  0.2688841166142232,
  0.3120624876849714,
  0.2593788853516079,
  0.27957461198211797,
  0.29653250827680505,
  0.3733057002713414,
  0.39932579346506986,
  0.2193929766990291,
  0.31025018026900864,
  0.27867135976798635,
  0.3270152135301575,
  0.29405211458992825,
  0.2145409027978942,
  0.309655408421556,
  0.3560095084679021,
  0.37798886278076904,
  0.20578386453685876,
  0.2967624050319473],
 'Newcastle United': [0.31608290952362705,
  0.23652104089163983,
  0.44547141349185543,
  0.4369866628545851,
  0.2896340456450191,
  0.19038960815312378,
  0.18944893555015252,
  0.43821397883795105,
  0.21823373458031775,
  0.23328906888076065,
  0.24993473840970284,
  0.2695353427828799,
  0.26845700563335917,
  0.30019483007906667,
  0.1339948460128415,
  0.27594469080948536,
  0.24505973435979825,
  0.30894011439573454,
  0.16513701056075164,
  0.19231818468757872,
  0.20794168038498648,
  0.35687041503289146,
  0.23450810558118387,
  0.2933655833732106,
  0.3383233655239428,
  0.36187415270906725,
  0.25635749001065683,
  0.2832652490358831,
  0.3841577245934219,
  0.3329072846899719,
  0.27960762490288593,
  0.2247336117662316,
  0.3535470968672128,
  0.2188575744939901,
  0.26415193381203084,
  0.20585239674096295,
  0.30003027724590886,
  0.18931646782070874],
 'West Ham United': [0.3563925274620585,
  0.35228351309842487,
  0.28530763096664397,
  0.21474108180234214,
  0.2303079832638242,
  0.35004415445079207,
  0.31039982743274175,
  0.2841952032000968,
  0.30521927988987363,
  0.39887458311285307,
  0.25664018533133487,
  0.1849241793777758,
  0.2880948562776643,
  0.2351407603536524,
  0.30118546361954757,
  0.23864182699693895,
  0.2016128178250321,
  0.3580592248782335,
  0.25452100460656263,
  0.33424251768686875,
  0.2879986211938807,
  0.23594138095545308,
  0.2275358479824123,
  0.17453051095031635,
  0.3834257632455417,
  0.2893873099149536,
  0.3320704615082594,
  0.3261546431488003,
  0.2486925692404264,
  0.46102125680319084,
  0.19407112361378479,
  0.3061722796099351,
  0.2824958126431328,
  0.3729407724171526,
  0.23707057652974597,
  0.3548692934240487,
  0.21464160388318068,
  0.2931485539459011],
 'Brighton & Hove Albion': [0.21070097620031789,
  0.23805346819366202,
  0.23575069641017643,
  0.32190260970860013,
  0.2825141095524221,
  0.265729735336137,
  0.26059687336346005,
  0.3032960401501457,
  0.2297032506138339,
  0.2181205115819225,
  0.3090197818830888,
  0.26260097427742096,
  0.35010994459163935,
  0.20723202379692937,
  0.2859090331838817,
  0.3437133440770333,
  0.2898644148005549,
  0.39147170092359324,
  0.26435202960147275,
  0.3204063348736811,
  0.3659110000282176,
  0.19239466612805103,
  0.289100742321931,
  0.37360266696422634,
  0.35778307463585224,
  0.3154817218909947,
  0.35701413976467905,
  0.2712368877804599,
  0.3817039238012328,
  0.2633928430705358,
  0.30372034072433024,
  0.2780366709981323,
  0.34004165175757606,
  0.2937911659503315,
  0.34433567163375994,
  0.3449956929154095,
  0.40285810752042295,
  0.15497970895884225],
 'Watford': [0.3392285186709556,
  0.3026570393541975,
  0.2613201080183011,
  0.26992765849741135,
  0.31550475352870677,
  0.33673397603734534,
  0.3241406631266834,
  0.3289237007659709,
  0.24975766054350354,
  0.3085559202515929,
  0.3138682198330757,
  0.33624932142440117,
  0.31195386613945114,
  0.22016017103082697,
  0.2807813445612986,
  0.34530803430319074,
  0.2019833189425886,
  0.3715367278183891,
  0.26732770532352285,
  0.3038868226523404,
  0.33438039560760513,
  0.2736663813077484,
  0.3070762541318905,
  0.3039182798497732,
  0.3864084092210981,
  0.32779484972339107,
  0.461758444298543,
  0.3511900282578799,
  0.414631632643221,
  0.3053264426639079,
  0.36001246077743937,
  0.4110834524054227,
  0.3226269102291647,
  0.2432507570027338,
  0.2885111661765906,
  0.23223725452269803,
  0.2818543041406482,
  0.30199052475236027],
 'Huddersfield Town': [0.316762773662688,
  0.15910408646799754,
  0.12460895202578429,
  0.35904351306996357,
  0.2874009588028634,
  0.38628394687940903,
  0.25069075077726166,
  0.3458789690894718,
  0.5397579495182196,
  0.21012393640780225,
  0.26423305622424337,
  0.328038563438045,
  0.22102385757645535,
  0.2286968190669654,
  0.23300388277121883,
  0.40813190504250013,
  0.3629136030418561,
  0.28174336059458416,
  0.39776459291954774,
  0.26537901093050315,
  0.23354735291020634,
  0.32478281954700383,
  0.3943103357611951,
  0.30396801409098473,
  0.25741779545141213,
  0.11920999434191454,
  0.41179789910953307,
  0.3177700116265882,
  0.1952538272800623,
  0.1618547473988508,
  0.4139310384822428,
  0.29379210894090546,
  0.3274698758612339,
  0.39764933684087606,
  0.325110716634788,
  0.2897932353206602,
  0.33576599033356685,
  0.22403185991668267],
 'Southampton': [0.1957437162219934,
  0.2680446183127152,
  0.2690266833451734,
  0.270093038322392,
  0.2977431082638832,
  0.2907590977943259,
  0.2846821602196301,
  0.30843276517649654,
  0.37958752292558284,
  0.32952704599681765,
  0.29318913930462903,
  0.41291103772498206,
  0.39465125025450004,
  0.4705650726872526,
  0.25423202248728416,
  0.28437934556615146,
  0.42766063109761737,
  0.3243539691345167,
  0.2716415343784903,
  0.2892768258209259,
  0.3572405162959646,
  0.3306973019458376,
  0.293162157389899,
  0.3579735505397748,
  0.1919763555662192,
  0.5054597766912129,
  0.28016144934320203,
  0.4401384122876864,
  0.3489997927972529,
  0.45905580589948425,
  0.4437237948292357,
  0.4675637185937113,
  0.42407162847751984,
  0.3759873986343535,
  0.31467566821274484,
  0.3828095371494705,
  0.43940169316365696,
  0.3978213300330504],
 'Swansea City': [0.4104187370411517,
  0.3054515450045085,
  0.33995328135520436,
  0.4416519463494099,
  0.15483059281252867,
  0.34241680392476376,
  0.3318096044160183,
  0.295043800836987,
  0.12405987383497638,
  0.3201285639218369,
  0.3222254967775245,
  0.35805128363595884,
  0.26270345053015626,
  0.22915595862660765,
  0.21788838740567554,
  0.3632418744638685,
  0.23945307832529153,
  0.3551797973774984,
  0.36729497076942147,
  0.44255899567157697,
  0.31383373635038864,
  0.1694818400451382,
  0.34471264239321203,
  0.37000776732960666,
  0.30155490616872777,
  0.3425984716274538,
  0.3568377048379366,
  0.35069811769619935,
  0.22745674247280984,
  0.36735537907975346,
  0.2689026777103397,
  0.3863027766245084,
  0.32998976010753717,
  0.1829937025499877,
  0.40629318112029716,
  0.35033440576717567,
  0.32108756490811285,
  0.2690864481794749],
 'Stoke City': [0.3288420575169141,
  0.20808791670929497,
  0.1756269618482867,
  0.2564899974497397,
  0.21236939512116937,
  0.21486118400340667,
  0.19769431588437503,
  0.24648264215514473,
  0.18047225075923637,
  0.17071737810284118,
  0.1744279495260532,
  0.36051606468590647,
  0.25679770381462635,
  0.20633640234847497,
  0.22566602338755407,
  0.28929381352300004,
  0.35492275257030464,
  0.3517711030092086,
  0.2680133079050089,
  0.26140234436180537,
  0.3295952315716338,
  0.26073607808801735,
  0.18880628848432351,
  0.29129899356845873,
  0.2643424727198014,
  0.3254515416544945,
  0.29743090913437953,
  0.2781384356424914,
  0.19538322253259477,
  0.31579561658653493,
  0.16131937211235806,
  0.1898380942708509,
  0.3214009237154981,
  0.3086624008648901,
  0.2514594564538409,
  0.3397017434733656,
  0.1521521514328246,
  0.21989091176421513],
 'West Bromwich Albion': [0.2970516077228328,
  0.15798501007257226,
  0.26808373423206777,
  0.270574343438235,
  0.235882620552318,
  0.37715597200306783,
  0.3194997389665067,
  0.2846211325969611,
  0.2723659522415821,
  0.27192914703171883,
  0.3026353707523549,
  0.3165619561294821,
  0.23505284871693383,
  0.18057295207405855,
  0.25559828899538545,
  0.2535616070353074,
  0.3265568798689063,
  0.26678954164265944,
  0.2927871014428694,
  0.3390708358758955,
  0.33880707031275226,
  0.22430411688854757,
  0.3002574909347036,
  0.29598114447965046,
  0.3001218656791219,
  0.205574100946062,
  0.2782599994811158,
  0.31983182652470654,
  0.19544261000950047,
  0.22101607969775677,
  0.254948067136326,
  0.2163774678923055,
  0.20766301894322842,
  0.22709290049049197,
  0.36844600171557634,
  0.2515131958456401,
  0.1579880555092802,
  0.1944795604196212]}